### ISSUE TITLE
how to add Domain into 01-telerising.lst

### ISSUE THREAD

**Issue by moovendran-368** [Publish3r/SniDust-Telerising#1]
i need add my Choice Domain list. How to add. please help me

**Comment by Publish3r** [comment]
You can add custom domains with your own domain file. https://github.com/Publish3r/SniDust-Telerising?tab=readme-ov-file#add-custom-domains
It's not possible to edit or remove the existing domain files, That's why i forked the project from https://github.com/Seji64/SniDust
