### ISSUE TITLE
Crontab error

### ISSUE THREAD

**Issue by fir3drag0n** [Publish3r/SniDust-Telerising#2]
Unfortunately, there is an error starting the container:

`[INFO] DynDNS Address in ALLOWED_CLIENTS detected => Enable cron job
/entrypoint.sh: line 37: /etc/crontabs/snidust: Permission denied`

How to solve this?

**Comment by Publish3r** [comment]
I have to update the changes from the original source: https://github.com/Seji64/SniDust
Maybe i have bext week time for it.

**Comment by Publish3r** [comment]
I have updated. Please delete the docker container and image. You have to deploy the current version. I don't know if it works, i'm not able to test it.
